pipeline {
  agent any
	stages {

		stage('Create kubernetes cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'devopsroot') {
					sh '''
						eksctl create cluster \
						--name capstonecluster \
						--version 1.17 \
						--nodegroup-name capstone-node-workers \
						--node-type t2.micro \
						--nodes 1 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-west-2 \
						--zones us-west-2a \
						--zones us-west-2b \
						--zones us-west-2c \
						--ssh-access \
						--ssh-public-key jenkin-access \
					'''
				}
			}
		}

    	stage('Create conf file cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'devopsroot') {
					sh '''
						aws eks --region us-west-2 update-kubeconfig --name capstonecluster
					'''
				}
			}
		} 
    }
}
